feat: sparql
Informasjonsforvaltning/rdf-diff-store pull request #15
Opened 2022-09-22 14:02 UTC by tenstad

Closes https://github.com/Informasjonsforvaltning/rdf-diff-store/issues/3

2022-09-23 06:08 UTC, NilsOveTen approved these changes
:sparkler:

2022-09-23 07:42 UTC, stigbd requested changes

2022-09-23 07:42 UTC, stigbd commented on openapi.yml
> +        '500':
Meiner å ha lest at ein ikkje treng å spesifisere "standard" returkoder med mindre ein avviker frå "det som er vanleg praksis". Du kan derfor vurdere å droppe disse frå openAPI-spekken.

2022-09-23 07:42 UTC, stigbd commented on tests/integration/test_integration.py
> +    """Test sparql endpoints."""
Innser at scenariet er komplisert. Det hadde derfor fortjent litt meir doc-string. Og kanskje ein og annan kommentar nedover i stegene.

2022-09-23 08:33 UTC, tenstad commented on tests/integration/test_integration.py
> +    """Test sparql endpoints."""
Det er kommentater nedover, og har nå også lagt til i docstring :+1:

2022-09-23 08:35 UTC, tenstad commented on openapi.yml
> +        '500':
Det er vel greit å se hva slags innhold man kan forvente å få ved en 500?

2022-09-27 10:34 UTC, stigbd approved these changes

2022-09-27 10:57 UTC, merged